import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'BelleBloom',
  description: 'Generated by create next app',
  preconnect: {
    rel: 'preconnect',
    url: 'https://fonts.googleapis.com',
  },
  preconnect: {
    rel: 'preconnect',
    url: 'https://fonts.gstatic.com',
  },
  preconnect: {
    rel: 'stylesheet',
    url: 'https://fonts.googleapis.com/css2?family=Anton&family=Bodoni+Moda:opsz@6..96&family=Climate+Crisis&family=Golos+Text&family=Oswald&family=Playfair+Display&family=Roboto&family=Shantell+Sans:ital,wght@1,300&family=Spectral:wght@300&family=Tilt+Neon&family=Ubuntu:ital@1&display=swap',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
